# Generated by Django 4.0.1 on 2022-01-18 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frexco', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrexcoDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('fruta', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Fruit',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
